# Generated by Django 6.0 on 2026-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_assignment_exam_quiz_assignmentsubmission_examresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
