# Generated by Django 6.0 on 2026-02-28 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_liveclass_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='assigned_student',
            field=models.ForeignKey(blank=True, help_text='Target specific student (Optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='student_class',
            field=models.CharField(blank=True, help_text='Target class (Optional)', max_length=20, null=True),
        ),
    ]
