# Generated by Django 6.0 on 2026-02-28 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_note_assigned_student_alter_note_student_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='audience_type',
            field=models.CharField(choices=[('ALL', 'All Students'), ('CLASS', 'Specific Class'), ('STUDENTS', 'Specific Students')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='specific_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_live_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='student_class',
            field=models.CharField(blank=True, help_text="Target class if Audience is 'Specific Class'", max_length=20, null=True),
        ),
    ]
