# Generated by Django 6.0 on 2026-03-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_liveclass_audience_type_liveclass_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
