# Generated by Django 6.0 on 2026-03-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_feedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='standard',
            field=models.IntegerField(blank=True, choices=[(10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], null=True),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='standard',
            field=models.IntegerField(blank=True, choices=[(10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='standard',
            field=models.IntegerField(blank=True, choices=[(10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='standard',
            field=models.IntegerField(blank=True, choices=[(10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='standard',
            field=models.IntegerField(blank=True, choices=[(10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], null=True),
        ),
    ]
