# Generated by Django 6.0 on 2026-03-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_assignmentsubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='target_class',
            field=models.IntegerField(blank=True, choices=[(10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], null=True),
        ),
    ]
