# Generated by Django 6.0 on 2026-03-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_liveclass_target_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='standard',
            field=models.IntegerField(choices=[(10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], default=10),
            preserve_default=False,
        ),
    ]
