# Generated by Django 6.0 on 2026-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_note_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='exams/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='target_class',
            field=models.IntegerField(blank=True, choices=[(10, 'Class 10'), (11, 'Class 11'), (12, 'Class 12')], null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
