# Generated by Django 6.0 on 2026-03-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_submitted_at_quizattempt_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
