# Generated by Django 6.0 on 2026-03-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_quiz_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='marks_obtained',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Graded', 'Graded')], default='Submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='teacher_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='total_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
