# Generated by Django 6.0 on 2026-03-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_examsubmission_graded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='doubts/'),
        ),
    ]
