# Generated by Django 6.0 on 2026-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_doubt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='admin_reply_attachment',
            field=models.FileField(blank=True, null=True, upload_to='doubt_replies/'),
        ),
    ]
