# Generated by Django 6.0.1 on 2026-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(choices=[('UAE', 'UAE (Dubai)'), ('Oman', 'Oman'), ('Qatar', 'Qatar'), ('Saudi Arabia', 'Saudi Arabia'), ('Kuwait', 'Kuwait'), ('Bahrain', 'Bahrain'), ('India', 'India'), ('Other', 'Other')], default='UAE', max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('student_class', models.CharField(blank=True, choices=[('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('Class 11', 'Class 11'), ('Class 12', 'Class 12'), ('Dropper', 'Dropper')], max_length=20, null=True)),
                ('subject', models.CharField(default='Physics', max_length=50)),
                ('place', models.CharField(blank=True, max_length=80, null=True)),
                ('tuition_type', models.CharField(blank=True, choices=[('Online 1:1', 'Online 1:1'), ('Online Group', 'Online Group'), ('Crash Course', 'Crash Course')], max_length=30, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Query',
                'verbose_name_plural': 'Contact Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
