# Generated by Django 6.0.1 on 2026-01-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactquery',
            options={},
        ),
        migrations.AlterField(
            model_name='contactquery',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('UAE (Dubai)', 'UAE (Dubai)'), ('Oman', 'Oman'), ('Qatar', 'Qatar'), ('Saudi Arabia', 'Saudi Arabia'), ('Kuwait', 'Kuwait'), ('Bahrain', 'Bahrain'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactquery',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
