# Generated by Django 6.0.1 on 2026-01-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_contactquery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactquery',
            name='country',
            field=models.CharField(choices=[('', 'Select Country'), ('India', 'India'), ('UAE (Dubai)', 'UAE (Dubai)'), ('Oman', 'Oman'), ('Qatar', 'Qatar'), ('Saudi Arabia', 'Saudi Arabia'), ('Kuwait', 'Kuwait'), ('Bahrain', 'Bahrain'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactquery',
            name='student_class',
            field=models.CharField(blank=True, choices=[('', 'Select Class'), ('Class 9', 'Class 9'), ('Class 10', 'Class 10'), ('Class 11', 'Class 11'), ('Class 12', 'Class 12'), ('Dropper', 'Dropper')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactquery',
            name='tuition_type',
            field=models.CharField(blank=True, choices=[('', 'Select Tuition Type'), ('Online 1:1', 'Online 1:1'), ('Online Group', 'Online Group'), ('Crash Course', 'Crash Course')], max_length=30, null=True),
        ),
    ]
